### PR TITLE
Add Feature to Allow Templating of Classpath Resources.

### PR DESCRIPTION
**Pull request by alexandre-normand**
I had the need to template a file that was from a shared module. The current version of `gstring-maven-plugin` only supports actual files. 

This PR adds support for `resources` and it looks for the paths on the classpath. 

This allows one to use a path coming from another artifact like this:

```
             <plugin>
                <groupId>org.jboss.tools.maven</groupId>
                <artifactId>gstring-maven-plugin</artifactId>
                <version>1.1.0-SNAPSHOT</version>
                <dependencies>
                    <dependency>
                        <groupId>other.groupId</groupId>
                        <artifactId>artifactIdWithTemplateResource</artifactId>
                        <version>1.0.0</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>create-script</id>
                        <phase>package</phase>
                        <goals>
                            <goal>process-templates</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>path/to/resource/in/dependency</resource>
                            </resources>
                            <symbols>
                                ...
                            </symbols>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

### CODE REVIEW

**Comment by mickaelistria** [comment]
This suggested feature is a very good idea, and PR looks good. I added a few comments to the PR to suggest a few necessary changes and suggestions.

**Comment by alexandre-normand** [comment]
Just pushed updates with the first round of comments.

**Comment by alexandre-normand** [comment]
I pushed another update with `IOUtils.closeQuietly()`. The reason I didn't use it yesterday was because I was reluctant to add a dependency (this lives under `org.apache.commons`:`commons-io`) but since you asked for it, I also think it's worth adding it for the readability. 

Thanks for reviewing!

**Comment by alexandre-normand** [comment]
Thanks @mickaelistria. Do you have an idea of when you might be pushing a `1.1.0` version?

**Comment by mickaelistria** [comment]
This change has been merged and a 1.1.0-SNAPSHOT version of gstring-maven-plugin is available on JBoss Snapshot repository.
Thanks for this good feature.

**Comment by mickaelistria** [comment]
It can happen soon. However, please ask this on the project forum so other potential contributors will be notified https://groups.google.com/forum/#!forum/gstring-maven-plugin

**Comment by alexandre-normand** [comment]
Will do. Thanks again.

**Pull request merged**
